#ifndef REACTOR_CORE_GLOBAL_H
#define REACTOR_CORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REACTOR_CORE_LIBRARY)
#  define REACTOR_CORE_EXPORT Q_DECL_EXPORT
#else
#  define REACTOR_CORE_EXPORT Q_DECL_IMPORT
#endif

#endif // REACTOR_CORE_GLOBAL_H
